/**
 * Derives the two generated artefacts from content/source.mjs:
 *
 *   supabase/migrations/0002_portfolio_seed.sql  — what the database holds
 *   client/src/data/content.json                 — what the bundle ships
 *
 * Keeping one authored source and generating both is the point: the API and
 * the offline fallback can never drift into saying different things about the
 * same job.
 *
 * Also audits the content for anything the requirements forbid shipping
 * (§9: no invented metrics, no placeholder text, no phone number) and for
 * assets that are still missing, and prints both lists.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import content from "../content/source.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// ── SQL literal helpers ─────────────────────────────────────────────────────

const sqlText = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`;

const sqlJson = (v) =>
  v === null || v === undefined ? "null" : `${sqlText(JSON.stringify(v))}::jsonb`;

const sqlBool = (v) => (v ? "true" : "false");
const sqlNum = (v) => (v === null || v === undefined ? "null" : String(v));

/** One INSERT ... ON CONFLICT DO UPDATE per table, so re-running is safe. */
function upsert(table, columns, rows) {
  if (!rows.length) return `-- ${table}: nothing to seed\n`;
  const cols = columns.map((c) => c.name);
  // The row index is passed through because some columns are derived from
  // position rather than from the row — experience order, for one.
  const values = rows
    .map((row, i) => `  (${columns.map((c) => c.value(row, i)).join(", ")})`)
    .join(",\n");
  const updates = cols
    .filter((c) => c !== "id")
    .map((c) => `${c} = excluded.${c}`)
    .join(",\n    ");
  return (
    `insert into public.${table} (${cols.join(", ")}) values\n${values}\n` +
    `on conflict (id) do update set\n    ${updates};\n`
  );
}

// ── The seed ────────────────────────────────────────────────────────────────

function buildSeed(c) {
  const parts = [
    `-- Generated by scripts/generate.mjs from content/source.mjs.`,
    `-- Do not edit by hand: edit the source and re-run \`npm run generate\`.`,
    ``,
    `begin;`,
    ``,
  ];

  parts.push(
    upsert(
      "portfolio_profile",
      [
        { name: "id", value: () => sqlText("primary") },
        { name: "name", value: (r) => sqlText(r.name) },
        { name: "role", value: (r) => sqlText(r.role) },
        { name: "employer", value: (r) => sqlText(r.employer) },
        { name: "location", value: (r) => sqlText(r.location) },
        { name: "positioning", value: (r) => sqlText(r.positioning) },
        { name: "email", value: (r) => sqlText(r.email) },
        { name: "links", value: (r) => sqlJson(r.links) },
        { name: "about", value: (r) => sqlJson(r.about) },
      ],
      [c.profile],
    ),
  );

  parts.push(
    upsert(
      "portfolio_experience",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "sort_order", value: (_r, i) => sqlNum((i + 1) * 10) },
        { name: "title", value: (r) => sqlText(r.title) },
        { name: "org", value: (r) => sqlText(r.org) },
        { name: "org_url", value: (r) => sqlText(r.orgUrl ?? null) },
        { name: "location", value: (r) => sqlText(r.location) },
        { name: "period", value: (r) => sqlText(r.period) },
        { name: "starts_on", value: (r) => sqlText(`${r.start}-01`) },
        { name: "ends_on", value: (r) => sqlText(r.end ? `${r.end}-01` : null) },
        { name: "summary", value: (r) => sqlText(r.summary) },
        { name: "note", value: (r) => sqlText(r.confidentialityNote ?? null) },
        { name: "tags", value: (r) => sqlJson(r.tags) },
      ],
      c.experience,
    ),
  );

  parts.push(
    upsert(
      "portfolio_education",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "sort_order", value: (_r, i) => sqlNum((i + 1) * 10) },
        { name: "qualification", value: (r) => sqlText(r.qualification) },
        { name: "org", value: (r) => sqlText(r.org) },
        { name: "finished", value: (r) => sqlText(r.finished) },
        { name: "result", value: (r) => sqlText(r.result) },
      ],
      c.education,
    ),
  );

  parts.push(
    upsert(
      "portfolio_awards",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "sort_order", value: (_r, i) => sqlNum((i + 1) * 10) },
        { name: "title", value: (r) => sqlText(r.title) },
        { name: "year", value: (r) => sqlText(r.year) },
      ],
      c.awards,
    ),
  );

  parts.push(
    upsert(
      "portfolio_skills",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "sort_order", value: (_r, i) => sqlNum((i + 1) * 10) },
        { name: "label", value: (r) => sqlText(r.label) },
        { name: "items", value: (r) => sqlJson(r.items) },
      ],
      c.skills,
    ),
  );

  parts.push(
    upsert(
      "portfolio_projects",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "sort_order", value: (r) => sqlNum(r.order) },
        { name: "title", value: (r) => sqlText(r.title) },
        { name: "kicker", value: (r) => sqlText(r.kicker) },
        { name: "one_liner", value: (r) => sqlText(r.oneLiner) },
        { name: "body", value: (r) => sqlText(r.body) },
        { name: "stack", value: (r) => sqlJson(r.stack) },
        { name: "link", value: (r) => sqlText(r.link) },
        { name: "link_note", value: (r) => sqlJson(r.linkNote ?? null) },
      ],
      c.projects,
    ),
  );

  parts.push(
    upsert(
      "portfolio_ambigrams",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "sort_order", value: (r) => sqlNum(r.order) },
        { name: "kind", value: (r) => sqlText(r.kind) },
        { name: "reads", value: (r) => sqlJson(r.reads) },
        { name: "note", value: (r) => sqlText(r.note ?? null) },
        { name: "year", value: (r) => sqlNum(r.year ?? null) },
        { name: "widths", value: (r) => sqlJson(r.widths) },
        { name: "featured", value: (r) => sqlBool(r.featured) },
        { name: "is_hero", value: (r) => sqlBool(r.hero) },
      ],
      c.ambigrams,
    ),
  );

  parts.push(
    upsert(
      "portfolio_case_studies",
      [
        { name: "id", value: (r) => sqlText(r.id) },
        { name: "slug", value: (r) => sqlText(r.slug) },
        { name: "title", value: (r) => sqlText(r.title) },
        { name: "role", value: (r) => sqlText(r.role) },
        { name: "period", value: (r) => sqlText(r.period) },
        { name: "repo", value: (r) => sqlText(r.repo) },
        { name: "summary", value: (r) => sqlText(r.summary) },
        { name: "sections", value: (r) => sqlJson(r.sections) },
        { name: "outcomes", value: (r) => sqlJson(r.outcomes) },
        { name: "photos", value: (r) => sqlJson(r.photos) },
        { name: "photos_note", value: (r) => sqlJson(r.photosNote ?? null) },
        { name: "video", value: (r) => sqlJson(r.video) },
      ],
      [c.caseStudy],
    ),
  );

  parts.push(`commit;`, ``);
  return parts.join("\n");
}

// ── Audit ───────────────────────────────────────────────────────────────────

/**
 * Requirements §9 forbids a few things reaching the built output. Cheap to
 * check mechanically, expensive to notice by eye at 2am before an interview.
 */
function audit(c) {
  const blob = JSON.stringify(c);
  const problems = [];
  const gaps = [];

  // §3: never publish the phone number. Any Bangladeshi mobile shape at all.
  if (/(?:\+?880|\b01)\d[\s-]?\d{4}[\s-]?\d{4}\b/.test(blob)) {
    problems.push("a phone number appears in the content");
  }
  if (/lorem ipsum/i.test(blob)) problems.push("lorem ipsum in the content");

  // Referee names are not in the content module at all; assert that stays true.
  if (/referee/i.test(blob)) problems.push("the word 'referee' appears");

  // Every TODO marker becomes a visible gap on the site and a line in the report.
  const walk = (node, trail) => {
    if (!node || typeof node !== "object") return;
    if (typeof node.__todo === "string") {
      gaps.push(`${trail}: ${node.__todo}`);
      return;
    }
    for (const [k, v] of Object.entries(node)) walk(v, trail ? `${trail}.${k}` : k);
  };
  walk(c, "");

  if (c.site.urlIsPlaceholder) {
    gaps.push("site.url: canonical domain is a placeholder (BLOCKING-2)");
  }
  if (!existsSync(path.join(root, "client/public/cv.pdf"))) {
    gaps.push("client/public/cv.pdf: missing — run `npm run assets`");
  }

  return { problems, gaps };
}

// ── Run ─────────────────────────────────────────────────────────────────────

const seed = buildSeed(content);
await mkdir(path.join(root, "supabase/migrations"), { recursive: true });
await writeFile(path.join(root, "supabase/migrations/0002_portfolio_seed.sql"), seed, "utf8");

await mkdir(path.join(root, "client/src/data"), { recursive: true });
await writeFile(
  path.join(root, "client/src/data/content.json"),
  JSON.stringify(content, null, 2) + "\n",
  "utf8",
);

const { problems, gaps } = audit(content);

console.log("generated:");
console.log("  supabase/migrations/0002_portfolio_seed.sql");
console.log("  client/src/data/content.json");

if (gaps.length) {
  console.log(`\nstill missing (${gaps.length}) — see docs/OPEN-ITEMS.md:`);
  for (const g of gaps) console.log(`  · ${g}`);
}

if (problems.length) {
  console.error(`\nWILL NOT SHIP (${problems.length}):`);
  for (const p of problems) console.error(`  ! ${p}`);
  process.exit(1);
}

// Keep the README's asset table honest about how many pieces exist.
const readme = path.join(root, "README.md");
if (existsSync(readme)) {
  const text = await readFile(readme, "utf8");
  const next = text.replace(
    /(<!-- counts -->)[\s\S]*?(<!-- \/counts -->)/,
    `$1\n${content.ambigrams.length} ambigrams · ${content.projects.length} projects · ${content.experience.length} roles\n$2`,
  );
  if (next !== text) await writeFile(readme, next, "utf8");
}
